language: python
python:
   - "3.5"
   - "3.6"
cache: pip
install: 
   - "pip install -r requirements.txt"
   - "import nltk"
   - "nltk.download('stopwords')"
script: 
   - python test_word_counter.py
   - pytest