language: python
os:
  - linux
dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.7"
addons:
  chrome: stable 

cache: pip

before_install:
   - sudo apt-get install chromium-chromedriver -y
   - sudo apt-get install python3-pip
   - sudo pip3 install virtualenv 
   - export PYTHONPATH="/home/travis/virtualenv/python3.7/lib/python3.6/site-packages"

install: 
   - pip install -r requirements.txt
   - pip install django --quiet

script: 
   - python -m nltk.downloader 'stopwords'
   - python -m unittest code_folder.tests.test_word_counter.KnownValues
   - python -m unittest code_folder.tests.test_twitter_word_counter.KnownValues
   - coverage run --source=code_folder/tests -m unittest discover -s code_folder/tests
   - coverage report code_folder/tests/*.py
   - source venv/bin/activate
   - echo a
   - python3.7 web/manage.py runserver
   - sleep 20
   - ps aux
   - curl localhost:8000
   - netstat -atu

after_success:
   - cd code_folder/tests/features
   - behave


