language: python
python:
   - "3.6"
cache: pip
env:
   - DJANGO_VERSION=1.4.1
before_install:
   - export PYTHONPATH="/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages"
install: 
   - "pip install -r requirements.txt"
   - "pip install django==$DJANGO_VERSION --quiet"
script: 
   - python -m nltk.downloader 'stopwords'
   - python -m unittest code_folder.tests.test_word_counter.KnownValues
   - python -m unittest code_folder.tests.test_twitter_word_counter.KnownValues
   - coverage run --source=code_folder/tests -m unittest discover -s code_folder/tests
   - coverage report code_folder/tests/*.py
   - source venv/bin/activate
   - python web/manage.py runserver
   - cd code_folder/tests/features
   - behave


