language: python
python:
   - "3.5"
   - "3.6"
cache: pip
install: 
   - "pip install -r requirements.txt"
script: 
   - python -m nltk.downloader 'stopwords'
   - python -m unittest src.tests.test_word_counter.KnownValues
   - coverage run src/tests/test_word_counter.py
   - coverage report -m src/tests/test_word_counter.py
   - python -m unittest src.tests.test_twitter_word_counter.KnownValues
   - coverage run src/tests/test_twitter_word_counter.py
   - coverage report -m src/tests/test_twitter_word_counter.py