language: python
os:
  - linux
python:
   - "3.6"
addons:
  chrome: stable

cache: pip
env:
   - DJANGO_VERSION=1.4.1
before_install:
   - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
   - unzip chromedriver_linux64.zip -d code_folder/tests/features/driver
   - cd code_folder/tests/features/driver
   - ls -l
   - export PYTHONPATH="/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages"

install: 
   - "pip install -r requirements.txt"
   - "pip install django==$DJANGO_VERSION --quiet"

script: 
   - python -m nltk.downloader 'stopwords'
   - python -m unittest code_folder.tests.test_word_counter.KnownValues
   - python -m unittest code_folder.tests.test_twitter_word_counter.KnownValues
   - coverage run --source=code_folder/tests -m unittest discover -s code_folder/tests
   - coverage report code_folder/tests/*.py

after_success:
   - cd code_folder/tests/features
   - behave


