language: python
python:
   - "3.6"
cache: pip
env:
   - DJANGO_VERSION=1.11.5
install: 
   - "pip install -r requirements.txt"
before_install:
   - export PYTHONPATH=$HOME/builds/JavierLima/Practical_final_testing
script: 
   - python -m nltk.downloader 'stopwords'
   - python -m unittest code_folder.tests.test_word_counter.KnownValues
   - python -m unittest code_folder.tests.test_twitter_word_counter.KnownValues
   - coverage run --source=code_folder/tests -m unittest discover -s code_folder/tests
   - coverage report code_folder/tests/*.py
   - source venv/bin/activate
   - pip instal django==$DJANGO --quiet
   - python web/manage.py runserver
   - cd code_folder/tests/features
   - behave


